### ISSUE TITLE
Regex matcher support for group names

### ISSUE THREAD

**Issue by ZyanKLee** [takkt-ag/esindex_exporter#3]
configuration could be improved/simplified by allowing to use the values of regex matcher groups in the group name fields.

Example:

```yaml
base_url: "https://our.internal.es.url"

groups:
- name: $1-alb.access
  index_patterns:
  - /([^-]+)-alb.access-.+/
```

**Comment by pitkley** [comment]
I have been thinking about this some more. I better understand the value of having regex support now, because not having to define a new group when a new environment is added or some new service is creating logs is definitely a very valuable feature.

My points about it being problematic to have the regex be part of the index-patterns still stand. But, instead, we can just make the regex-pattern be a single (optional) field on the group instead:

```yaml
groups:
- name: ${environment}-alb.access
  index_patterns:
  - *-alb.access-*
  grouping_pattern: '^(?<environment>[^-]+)-alb.access'
```

This way we can still fully leverage the multi-target syntax and don't have to worry about multiple incompatible patterns. Instead we just iterate over the rows ElasticSearch returns, try to match each index name to the pattern and if it matches include it in the result, or ignore it otherwise (with a warning-log so the user knows that something might be not quite right).

I also think that this is what we need to make this most useful for our use-case, too.
